version: '3.4'

services:

  eachother:
    image: lixinyang/eachother
    ports:
      - "8081:80"
    depends_on:
      - database
    restart: always
    volumes:
      - ./appsettings.json:/app/appsettings.json
      - ./data:/home

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
