name: Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      run: docker build --tag lixinyang/eachother:latest .
    
    - name: Push image to DockerHub
      run: |
        docker login -u lixinyang -p ${{ secrets.DOCKERHUB_PASSWORD }}
        docker push lixinyang/eachother:latest
        docker logout

    - name: Push image to aliyun
      run: |
        docker login -u=lllxy啊啊啊 -p ${{ secrets.DOCKERHUB_PASSWORD }} registry.cn-shenzhen.aliyuncs.com
        docker tag lixinyang/eachother:latest registry.cn-shenzhen.aliyuncs.com/lllxy/eachother:latest
        docker push registry.cn-shenzhen.aliyuncs.com/lllxy/eachother:latest
        docker logout
